---
mysql_root_password: root

mysql_databases:
  - name: "{{ db_write.name }}"
    port: "{{ db_write.port }}"
    encoding: "{{ db_write.encoding }}"
    collation: "{{ db_write.collation }}"

mysql_users:
  - name: "{{ db_write.username }}"
    host: "%"
    password: "{{ db_write.password }}"
    priv: "{{ db_write.username }}.*:ALL"

php_version: '7.1'

php_packages_extra:
  - php-apcu
  - php-cli
  - php-common
  - php-curl
  - php-fpm
  - php-intl
  - php-mbstring
  - php-mysql
  - php-xml

php_webserver_daemon: "nginx"

php_enable_php_fpm: true
php_fpm_listen: "/var/run/php/php{{ php_version }}-fpm.sock"
php_fpm_listen_allowed_clients: "/var/run/php/php{{ php_version }}-fpm.sock"
php_expose_php: "False"
php_memory_limit: "256M"
php_date_timezone: "UTC"

